### ISSUE TITLE
Unhandled error event

### ISSUE THREAD

**Issue by kanyawest** [tjhorner/steam-goddammit-bot#1]
Hello, thanks for making this awesome bot

I used it this morning and it worked fine, I was able to customize everything on my own

However, after I did a fresh npm install, I keep getting an error upon starting app.js
This is the error http://i.imgur.com/CYNWyoe.jpg

Thanks in advance!

edit: nevermind forgot brackets

**Comment by tjhorner** [comment]
So you got it to work? I should document this error in the README for others.

**Comment by tjhorner** [comment]
Also I world love to see your bot :)
